/**
 * generate-stats.js
 * 扫描构建产物 + 读取 config.js，生成 site-stats.json 与 site-stats.js（供 file:// 本地打开时注入统计，避免 fetch CORS）
 * 运行方式：node generate-stats.js
 */

const fs = require('fs');
const path = require('path');

const WEBSITE = __dirname;
const DOCS_DIR = path.join(WEBSITE, 'docs');
const OUTPUT_JSON = path.join(WEBSITE, 'site-stats.json');
const OUTPUT_JS = path.join(WEBSITE, 'site-stats.js');

function countFiles(dir) {
    let count = 0;
    if (!fs.existsSync(dir)) return count;
    fs.readdirSync(dir, { withFileTypes: true }).forEach(entry => {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            count += countFiles(full);
        } else if (entry.name.endsWith('.html')) {
            count++;
        }
    });
    return count;
}

function scanModule(slug) {
    const modulePath = path.join(DOCS_DIR, slug);
    if (!fs.existsSync(modulePath)) return null;

    const stat = fs.statSync(modulePath);
    if (!stat.isDirectory()) return null;

    const children = fs.readdirSync(modulePath);
    const isVersioned = children.some(n => /^\d+\.\d+/.test(n));

    if (isVersioned) {
        const configVersions = getConfigVersions(slug);
        const versions = {};
        configVersions.forEach(version => {
            const versionDir = path.join(modulePath, version);
            if (fs.existsSync(versionDir)) {
                versions[version] = {
                    tutorials: countFiles(path.join(versionDir, 'tutorials')),
                    analysis: countFiles(path.join(versionDir, 'analysis'))
                };
            }
        });
        return { isVersioned: true, versions };
    } else {
        return {
            isVersioned: false,
            tutorials: countFiles(path.join(modulePath, 'tutorials')),
            analysis: countFiles(path.join(modulePath, 'analysis'))
        };
    }
}

function getConfigVersions(slug) {
    const configPath = path.join(WEBSITE, 'scripts', 'config.js');
    const code = fs.readFileSync(configPath, 'utf-8');
    const blockMatch = code.match(/\/\/ =+\n\/\/ 模组配置[^\n]*\n\/\/ =+\n[\s\S]*?const modules = \{([\s\S]*?)\n};/);
    if (!blockMatch) return [];
    const slugRe = new RegExp(`${slug}:\\s*\\{[^}]*?versions:\\s*\\[([^\\]]+)\\]`, 'm');
    const m = slugRe.exec(blockMatch[1]);
    if (!m) return [];
    return m[1].split(',').map(v => v.trim().replace(/['"]/g, '')).filter(Boolean);
}

function getConfigModules() {
    const configPath = path.join(WEBSITE, 'scripts', 'config.js');
    const code = fs.readFileSync(configPath, 'utf-8');
    const blockMatch = code.match(/\/\/ =+\n\/\/ 模组配置[^\n]*\n\/\/ =+\n[\s\S]*?const modules = \{([\s\S]*?)\n};/);
    if (!blockMatch) return [];
    const re = /^\s+(\w+):\s*\{/gm;
    const slugs = [];
    let m;
    while ((m = re.exec(blockMatch[1])) !== null) slugs.push(m[1]);
    return slugs;
}

// ── 主逻辑 ──────────────────────────────────────────────────
const slugs = getConfigModules();
console.log(`发现模组: ${slugs.join(', ')}`);

const stats = {
    generated: new Date().toISOString(),
    totalDocs: 0,
    totalModules: slugs.length,
    mcVersions: [],
    modules: {}
};

slugs.forEach(slug => {
    const result = scanModule(slug);
    if (!result) {
        console.warn(`  ⚠  未找到 ${slug} 的文档目录`);
        return;
    }

    const total = result.isVersioned
        ? Object.values(result.versions).reduce((s, v) => s + (v.tutorials || 0) + (v.analysis || 0), 0)
        : ((result.tutorials || 0) + (result.analysis || 0));

    stats.modules[slug] = result;

    if (result.isVersioned) {
        const vers = Object.keys(result.versions);
        stats.mcVersions = vers; // 用 config 里的顺序
        stats.modules[slug].defaultVersion = vers[0];
        console.log(`  ✓  ${slug}（${vers.join(', ')}）: ${total} 篇`);
    } else {
        console.log(`  ✓  ${slug}: ${total} 篇`);
    }

    stats.totalDocs += total;
});

const json = JSON.stringify(stats, null, 2);
fs.writeFileSync(OUTPUT_JSON, json);
const jsBody = `/** Generated by generate-stats.js — do not edit */\nwindow.__SITE_STATS__ = ${JSON.stringify(stats)};\n`;
fs.writeFileSync(OUTPUT_JS, jsBody);
console.log(`\n✅ site-stats.json → ${OUTPUT_JSON}`);
console.log(`✅ site-stats.js   → ${OUTPUT_JS}`);
console.log(`   总文档 ${stats.totalDocs} | 模组 ${stats.totalModules} | MC 版本 ${stats.mcVersions.join(', ')}`);
